project_name: nextbike

before:
  hooks:
    - go mod tidy

builds:
  - id: nextbike
    main: ./cmd/nextbike
    binary: nextbike
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    builds:
      - nextbike
    name_template: >-
      {{ .ProjectName }}_
      {{ .Version }}_
      {{ .Os }}_
      {{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  github:
    owner: PatrickSteil
    name: nextbike

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
